
export const disposableEmailDomains = new Set([
  '0-mail.com', '027168.com', '0815.ru', '0815.su', '0clickemail.com', '0wnd.net', '0wnd.org',
  '10mail.org', '10minutemail.co.uk', '10minutemail.com', '123-m.com', '1ch.us', '1mail.ml',
  '1pad.de', '1up.pt', '20mail.it', '20minutemail.com', '21cn.com', '24hourmail.com',
  '2fdgdfgdfgdf.tk', '2prong.com', '30minutemail.com', '33mail.com', '3d-painting.com',
  '4warding.com', '4warding.net', '4warding.org', '50e.info', '5mail.cf', '5ymail.com',
  '60minutemail.com', '675hosting.com', '675hosting.net', '675hosting.org', '6ip.us',
  '6url.com', '75hosting.com', '75hosting.net', '75hosting.org', '7days-printing.com',
  '7mail.ml', '8mail.cf', '8mail.ga', '8mail.gq', '9mail.cf', 'a-bc.net', 'abusemail.de',
  'acentri.com', 'advantimo.com', 'afrobacon.com', 'ag.us.to', 'agedmail.com', 'ajaxapp.net',
  'alivance.com', 'amail.club', 'amilegit.com', 'amiri.net', 'amiri.org', 'anappthat.com',
  'ano-mail.net', 'anonbox.net', 'anonymail.dk', 'anonymbox.com', 'antichef.com',
  'antichef.net', 'antispam.de', 'antispam24.de', 'appixie.com', 'armyspy.com', 'aver.com',
  'azmeil.tk', 'baxomale.ht.cx', 'beddly.com', 'beefmilk.com', 'bigstring.com', 'binkmail.com',
  'bio-muesli.info', 'bio-muesli.net', 'boun.cr', 'bouncr.com', 'breakthru.com',
  'brennendesreich.de', 'broadbandninja.com', 'bsnow.net', 'bspamfree.org', 'btybat.com',
  'bugmenot.com', 'burnsender.com', 'cashette.com', 'centermail.com', 'centermail.net',
  'chacuo.net', 'chammy.info', 'cheaphub.net', 'chogmail.com', 'choicemail1.com', 'clixser.com',
  'cmail.club', 'cmail.com', 'cmail.net', 'cmail.org', 'coldemail.info', 'consumerriot.com',
  'cool.fr.nf', 'courriel.fr.nf', 'courrieltemporaire.com', 'crapmail.org', 'cubiclink.com',
  'curryworld.de', 'cust.in', 'cuvox.de', 'dacoolest.com', 'dandikmail.com', 'dayrep.com',
  'deadaddress.com', 'deadspam.com', 'deagot.com', 'dealja.com', 'despam.it',
  'despammed.com', 'devnullmail.com', 'dfgh.net', 'digitalsanctuary.com', 'dingbone.com',
  'discard.cf', 'discard.email', 'discard.ga', 'discard.gq', 'discard.ml', 'discard.tk',
  'disposable-email.ml', 'disposable.cf', 'disposable.ga', 'disposable.ml',
  'disposableaddress.com', 'disposableemailaddresses.com', 'disposableinbox.com',
  'dispose.it', 'disposeamail.com', 'disposemail.com', 'dispostable.com', 'divermail.com',
  'dm.w3internet.co.uk', 'dodgeit.com', 'dodgit.com', 'dodgit.org', 'donemail.ru',
  'dontreg.com', 'dontsendmespam.de', 'drdrb.com', 'drdrb.net', 'drdrb.org',
  'droplar.com', 'dropmail.me', 'dudmail.com', 'dump-email.info', 'dumpandjunk.com',
  'dumpmail.de', 'dumpyemail.com', 'e-mail.com', 'e-mail.org', 'e4ward.com',
  'easytrashmail.com', 'einrot.com', 'einrot.de', 'email-fake.cf', 'email-fake.ga',
  'email-fake.gq', 'email-fake.ml', 'email-fake.tk', 'email60.com', 'emailage.cf',
  'emailage.ga', 'emailage.gq', 'emailage.ml', 'emailage.tk', 'emaildienst.de',
  'emailgo.de', 'emailias.com', 'emailigo.de', 'emailinfive.com', 'emailisvalid.com',
  'emaillime.com', 'emailmiser.com', 'emailproxsy.com', 'emails.ga', 'emailsensei.com',
  'emailspam.cf', 'emailspam.ga', 'emailspam.gq', 'emailspam.ml', 'emailspam.tk',
  'emailtemporar.ro', 'emailtemporario.com.br', 'emailthe.net', 'emailto.de', 'emailwarden.com',
  'emailx.at.hm', 'emailxfer.com', 'emeil.in', 'emeil.ir', 'emz.net', 'enterto.com',
  'ephemail.net', 'est.une.victime.de.spammeurs.com', 'etranquil.com', 'etranquil.net',
  'etranquil.org', 'everytg.ml', 'explodemail.com', 'eyepaste.com', 'fake-mail.cf',
  'fake-mail.ga', 'fake-mail.gq', 'fake-mail.ml', 'fake-mail.tk', 'fakeinbox.cf',
  'fakeinbox.com', 'fakeinbox.ga', 'fakeinbox.gq', 'fakeinbox.ml', 'fakeinbox.tk',
  'fakemail.fr', 'fakemailgenerator.com', 'fakemailz.com', 'fammix.com', 'fastacura.com',
  'fastchevy.com', 'fastchrysler.com', 'fastkawasaki.com', 'fastmazda.com',
  'fastmitsubishi.com', 'fastnissan.com', 'fastsubaru.com', 'fastsuzuki.com',
  'fasttoyota.com', 'fastyamaha.com', 'fatflap.com', 'fdfdsfds.com', 'fightallspam.com',
  'fiifke.de', 'filzmail.com', 'fixmail.tk', 'fleckens.hu', 'flemail.ru', 'flurred.com',
  'flyspam.com', 'footard.com', 'forgetmail.com', 'fornow.eu', 'fr33mail.info',
  'frapmail.com', 'freecoolemail.com', 'free-email.cf', 'free-email.ga', 'freemail.ms',
  'freemail.t-com.hr', 'freemails.cf', 'freemails.ga', 'freemails.ml', 'freemail.hu',
  'freundin.ru', 'friendlymail.co.uk', 'front14.org', 'fuckingduh.com', 'fudgerub.com',
  'fux0ringduh.com', 'fw.moza.pl', 'g.hmail.us', 'garliclife.com', 'gawab.com',
  'gelitik.in', 'get-mail.cf', 'get-mail.ga', 'get-mail.ml', 'get-mail.tk',
  'get1mail.com', 'get2mail.fr', 'getairmail.com', 'getmails.eu', 'getnada.com',
  'getonemail.com', 'getonemail.net', 'ghosttexter.de', 'giantmail.de', 'girlsundertheinfluence.com',
  'gishpuppy.com', 'gmal.com', 'gmatch.org', 'goemailgo.com', 'gorillaswithdirtyarmpits.com',
  'gotmail.com', 'gotmail.net', 'gotmail.org', 'gotti.otherinbox.com', 'gowikibay.com',
  'gree.gq', 'greensloth.com', 'grr.la', 'gsrv.co.uk', 'guerillamail.biz',
  'guerillamail.com', 'guerillamail.de', 'guerillamail.net', 'guerillamail.org',
  'guerrillamail.biz', 'guerrillamail.com', 'guerrillamail.de', 'guerrillamail.net',
  'guerrillamail.org', 'gustr.com', 'h.thc.lv', 'h8s.org', 'haltospam.com',
  'hatespam.org', 'hellodream.mobi', 'hidemail.de', 'hidemail.pro', 'hidemail.us',
  'hitbts.com', 'hmamail.com', 'hochsitze.com', 'hoer.pw', 'honryou.com',
  'hot-mail.cf', 'hot-mail.ga', 'hot-mail.gq', 'hot-mail.ml', 'hot-mail.tk',
  'hotpop.com', 'hulapla.de', 'hush.com', 'hushmail.com', 'i.ua', 'ieatspam.eu',
  'ieatspam.info', 'ieh-mail.de', 'ihateyoualot.info', 'iheartspam.org', 'ikbenspamvrij.nl',
  'imails.info', 'imgof.com', 'imstations.com', 'inbax.tk', 'inbox.si', 'inboxalias.com',
  'inboxbear.com', 'inboxclean.com', 'inboxclean.org', 'inboxdesign.me', 'inboxed.im',
  'inboxed.pw', 'inboxproxy.com', 'inboxstore.me', 'incognitomail.com', 'incognitomail.net',
  'incognitomail.org', 'info-radio.ml', 'instant-mail.de', 'ipoo.org', 'irish2me.com',
  'iwi.net', 'jetable.com', 'jetable.fr.nf', 'jetable.net', 'jetable.org', 'jnxjn.com',
  'jourrapide.com', 'junk1e.com', 'junkmail.ga', 'junkmail.gq', 'kamarome.com',
  'kasmail.com', 'kaspop.com', 'keepmymail.com', 'killmail.com', 'killmail.net',
  'kimsdisk.com', 'kir.ch.tc', 'klassmaster.com', 'klassmaster.net', 'klzlk.com',
  'kmhow.com', 'kostenlose.ws', 'kpooa.com', 'kulturbenoetigt.de', 'kurzepost.de',
  'l33r.eu', 'lackmail.net', 'lackmail.ru', 'lags.us', 'landmail.co', 'lass.pw',
  'last-chance.pro', 'lastmail.co', 'lastmail.com', 'lazyinbox.com', 'leeching.net',
  'letthemeatspam.com', 'lhsdv.com', 'lifebyfood.com', 'link2mail.net', 'litedrop.com',
  'liveradio.tk', 'lolfreak.net', 'lolfreak.net', 'lol.ovpn.to', 'lroid.com',
  'lr78.com', 'lukop.dk', 'm21.cc', 'm4ilweb.info', 'mail-filter.com', 'mail-temporaire.fr',
  'mail.by', 'mail.mezimages.net', 'mail.zp.ua', 'mail114.net', 'mail1a.de', 'mail21.cc',
  'mail2rss.org', 'mail333.com', 'mail4trash.com', 'mailbidon.com', 'mailbiz.biz',
  'mailblocks.com', 'mailbucket.org', 'mailcat.biz', 'mailcatch.com', 'mailde.de',
  'mailde.info', 'maildrop.cc', 'maildrop.cf', 'maildrop.ga', 'maildrop.gq', 'maildrop.ml',
  'maildx.com', 'maileater.com', 'mailed.ro', 'maileimer.de', 'mailexpire.com',
  'mailfa.tk', 'mail-fake.com', 'mailfall.com', 'mailforspam.com', 'mailfree.ga',
  'mailfree.gq', 'mailfree.ml', 'mailfreeonline.com', 'mailfs.com', 'mailguard.me',
  'mailhero.io', 'mailimate.com', 'mailin8r.com', 'mailinater.com', 'mailinator.com',
  'mailinator.net', 'mailinator.org', 'mailinator.us', 'mailinator2.com', 'mailinblack.com',
  'mailinculator.com', 'mailismagic.com', 'mailita.tk', 'mailjunk.cf', 'mailjunk.ga',
  'mailjunk.gq', 'mailjunk.ml', 'mailjunk.tk', 'mailmate.com', 'mailme.gq', 'mailme.ir',
  'mailme.lv', 'mailme24.com', 'mailmetrash.com', 'mailmoat.com', 'mailmoth.com',
  'mailms.com', 'mailna.co', 'mailna.in', 'mailna.me', 'mailnator.com', 'mailnesia.com',
  'mailnull.com', 'mailpick.biz', 'mailproxsy.com', 'mailquack.com', 'mailrock.biz',
  'mailsac.com', 'mailscheap.us', 'mailseal.de', 'mailshell.com', 'mailshiv.com',
  'mailsiphon.com', 'mailslapper.com', 'mailslite.com', 'mailtemp.info', 'mail-temporaire.fr',
  'mailtemporaire.com', 'mailtemporaire.fr', 'mailtome.de', 'mailtothis.com', 'mailtrash.net',
  'mailtrix.net', 'mailtv.net', 'mailtv.tv', 'mailwithyou.com', 'mailzilla.com',
  'mailzilla.org', 'mailzi.ru', 'makemetheking.com', 'mamber.net', 'manybrain.com',
  'mbx.cc', 'mciek.com', 'mega.zik.dj', 'meinspamschutz.de', 'meltmail.com',
  'messagebeamer.de', 'messwiththebestdieliketherest.com', 'mezimages.net', 'mfsa.info', 'mfsa.ru',
  'miafer.de', 'midcoastcustoms.com', 'midcoastsolutions.com', 'midcoastsolutions.net',
  'midlertidig.com', 'mierdamail.com', 'migmail.pl', 'migumail.com', 'mintemail.com',
  'mjukglass.nu', 'moakt.com', 'mohmal.com', 'moncourrier.fr.nf', 'monemail.fr.nf',
  'monmail.fr.nf', 'monumentmail.com', 'msa.minsmail.com', 'mt2009.com', 'mt2014.com',
  'mt2015.com', 'mx0.wwwnew.eu', 'my10minutemail.com', 'myadult.info', 'mycleaninbox.net',
  'myemail.dk', 'my-email.gq', 'my-email.ml', 'my-mail.gq', 'my-mail.ml',
  'myfakeinbox.com', 'mymail-in.net', 'mymail.infos.st', 'mymail.net.ru', 'mynetstore.de',
  'my-spam.gq', 'my-spam.ml', 'my-temp-mail.gq', 'my-temp-mail.ml', 'mytemp.email',
  'mytempemail.com', 'mytempmail.com', 'mytrashmail.com', 'mytrashmail.com', 'nabuma.com',
  'neomailbox.com', 'nepwk.com', 'nervmich.net', 'nervtmich.net', 'netmails.com',
  'netmails.net', 'netricity.nl', 'netris.de', 'netzidiot.de', 'neverbox.com',
  'nevermail.de', 'nice-4u.com', 'nincsmail.com', 'nmail.cf', 'nmail.ga', 'no-spam.ws',
  'nobulk.com', 'noclickemail.com', 'nogmailspam.info', 'nomail.cf', 'nomail.ga',
  'nomail.pw', 'nomail.xl.cx', 'nomail2me.com', 'nomorespamemails.com', 'nonspam.eu',
  'nonspammer.de', 'noref.in', 'nospam.wins.com.br', 'nospam.ze.tc', 'nospam4.us',
  'nospamfor.us', 'nospammail.net', 'nospamthanks.info', 'notmailinator.com', 'notsharingmy.info',
  'nowhere.org', 'nowmymail.com', 'ntlhelp.net', 'nurfuerspam.de', 'nus.edu.sg',
  'nwldx.com', 'objectmail.com', 'obobbo.com', 'odaymail.com', 'odnorazovoe.ru',
  'ohaaa.de', 'omail.pro', 'one-time.email', 'oneoffemail.com', 'oneoffmail.com',
  'onewaymail.com', 'onlatedotcom.info', 'online.ms', 'oopi.org', 'opayq.com',
  'opm.us', 'opm.gov', 'orangatango.com', 'ordinaryamerican.net', 'otherinbox.com',
  'ourklips.com', 'outlawspam.com', 'ovpn.to', 'owlpic.com', 'p.fackme.gq', 'pancakemail.com',
  'parl.org.uk', 'partybombe.de', 'pepbot.com', 'pfui.ru', 'phreaker.net',
  'pimpedupmyspace.com', 'pjjkp.com', 'plexolan.de', 'poczta.onet.pl', 'politiker-ci.de',
  'pookmail.com', 'porco.cf', 'porco.ga', 'porco.gq', 'porco.ml', 'porco.tk',
  'poutineyourface.com', 'premium-mail.com', 'privacy.net', 'privatdemail.net', 'privy-mail.com',
  'privymail.de', 'proxymail.eu', 'proxytemp.org', 'prtnx.com', 'punkass.com',
  'putthisinyourspamdatabase.com', 'pwrby.com', 'q.awl2.net', 'qasti.com', 'qisdo.com',
  'qiso.com', 'qq.com', 'quickinbox.com', 'quickmail.nl', 'rcpt.at', 're-gister.com',
  'reallymymail.com', 'realtyalerts.ca', 'receiveee.com', 'recode.me', 'reconmail.com',
  'regbypass.com', 'regbypass.comsafe-mail.net', 'rejectmail.com', 'remail.cf', 'remail.ga',
  'resged.com', 'rhyta.com', 'rklips.com', 'rmqke.com', 'rppkn.com', 'rtrtr.com',
  's.dext.com', 's.fackme.gq', 's0ny.net', 'safe-mail.net', 'safersignup.de',
  'safetymail.info', 'safetypost.de', 'sandelf.de', 'saynotospam.com', 'scatmail.com',
  'schafmail.de', 'schmeissweg.tk', 'schrott-email.de', 'secmail.pw', 'secretemail.de',
  'secure-mail.biz', 'secure-mail.cc', 'selfdestructingmail.com', 'selfdestructingmail.org',
  'sendspamhere.com', 'senseless-entertainment.com', 'server.ms', 'services.com', 'shared-mail.com',
  'sharklasers.com', 'shieldedmail.com', 'shieldemail.com', 'shiftmail.com', 'shitaway.cf',
  'shitaway.ga', 'shitaway.gq', 'shitaway.ml', 'shitaway.tk', 'shitmail.me',
  'shitmail.org', 'shitware.nl', 'shmeriously.com', 'shortmail.net', 'shotmail.ru',
  'showslow.com', 'sibmail.com', 'sinnlos-mail.de', 'siteposter.net', 'skeefmail.com',
  'slaskpost.se', 'slave-auctions.net', 'slopsbox.com', 'slushmail.com', 'smashmail.de',
  'smellfear.com', 'smellmyfinger.com', 'snakemail.com', 'sneakemail.com', 'sneakmail.de',
  'snkmail.com', 'sofimail.com', 'sofort-mail.de', 'sogetthis.com', 'sohu.com',
  'solvemail.info', 'soodomail.com', 'soodonims.com', 'spam.la', 'spam.su',
  'spam4.me', 'spamail.de', 'spamarrest.com', 'spambob.com', 'spambob.net',
  'spambob.org', 'spambog.com', 'spambog.de', 'spambog.ru', 'spambox.info',
  'spambox.irishspringrealty.com', 'spambox.us', 'spamcero.com', 'spamcon.org', 'spamcorptastic.com',
  'spamcowboy.com', 'spamcowboy.net', 'spamcowboy.org', 'spamday.com', 'spamdecoy.net',
  'spamex.com', 'spamfighter.cf', 'spamfighter.ga', 'spamfighter.gq', 'spamfighter.ml',
  'spamfighter.tk', 'spamfree.eu', 'spamfree24.com', 'spamfree24.de', 'spamfree24.eu',
  'spamfree24.info', 'spamfree24.net', 'spamfree24.org', 'spamgoes.in', 'spamgourmet.com',
  'spamgourmet.net', 'spamgourmet.org', 'spamherelots.com', 'spamhereplease.com', 'spamhole.com',
  'spamify.com', 'spaminator.de', 'spamkill.info', 'spaml.com', 'spaml.de',
  'spammotel.com', 'spamobox.com', 'spamoff.de', 'spamsalad.in', 'spamslicer.com',
  'spamstack.net', 'spamthis.co.uk', 'spamthisplease.com', 'spamtrail.com', 'spamtrap.co',
  'spamtrap.it', 'spamwc.cf', 'spamwc.ga', 'spamwc.gq', 'spamwc.ml',
  'speed.1s.fr', 'sperma.cf', 'sperma.ga', 'sperma.gq', 'sperma.ml', 'spikio.com',
  'spoofmail.de', 'spybox.de', 'squizzy.de', 'ssoia.com', 'startkeys.com',
  'stinkefinger.net', 'stop-my-spam.com', 'stuffmail.de', 'super-auswahl.de', 'supergreatmail.com',
  'supermailer.jp', 'superrito.com', 'superstachel.de', 'suremail.info', 'svk.jp',
  'sweetxxx.de', 't.psh.me', 'tafmail.com', 'tagyourself.com', 'talkinator.com',
  'tapchicuoi.net', 'tapchicuoi.org', 'taskforcemail.com', 'teewars.org', 'teleworm.com',
  'teleworm.us', 'temp-mail.com', 'temp-mail.de', 'temp-mail.org', 'tempail.com',
  'tempalias.com', 'tempemail.co', 'tempemail.com', 'tempemail.net', 'tempinbox.co.uk',
  'tempinbox.com', 'tempmail.co', 'tempmail.eu', 'tempmail.it', 'tempmail.us',
  'temp-mail.ru', 'tempmail2.com', 'tempmaildemo.com', 'tempmailer.com', 'tempmailer.de',
  'tempomail.fr', 'temporarily.de', 'temporarioemail.com.br', 'temporaryemail.net',
  'temporaryemail.us', 'temporaryforwarding.com', 'temporaryinbox.com', 'temporarymailaddress.com',
  'tempthe.net', 'tempymail.com', 'tfwno.gf', 'thankyou2010.com', 'thecloudindex.com',
  'thisisnotmyrealemail.com', 'thismail.net', 'thrma.com', 'throam.com', 'thrott.com',
  'throwam.com', 'throwawayemailaddress.com', 'throwawaymail.com', 'tilien.com', 'tittbit.in',
  'tizi.com', 'tmail.com', 'tmail.ws', 'tmailinator.com', 'toiea.com',
  'tokem.co', 'toomail.biz', 'top100.tk', 'top1mail.com', 'top1mail.net',
  'topmail-files.de', 'tormail.org', 'tradermail.info', 'trash-amil.com', 'trash-mail.at',
  'trash-mail.ca', 'trash-mail.cf', 'trash-mail.com', 'trash-mail.de', 'trash-mail.ga',
  'trash-mail.gq', 'trash-mail.ml', 'trash-mail.tk', 'trash2009.com', 'trash2010.com',
  'trash2011.com', 'trashcanmail.com', 'trashdevil.com', 'trashdevil.de', 'trashemail.de',
  'trashmail.at', 'trashmail.ca', 'trashmail.com', 'trashmail.de', 'trashmail.me',
  'trashmail.net', 'trashmail.org', 'trashmail.ws', 'trashmailer.com', 'trashymail.com',
  'trashymail.net', 'trayna.com', 'trbvm.com', 'trbvn.com', 'trickmail.net',
  'trillianpro.com', 'tryalert.com', 'turual.com', 'twinmail.de', 'tyldd.com',
  'u.dmarc.io', 'uacro.com', 'ubismail.net', 'uggsrock.com', 'uk.to',
  'umail.net', 'unmail.ru', 'upliftnow.com', 'uplipht.com', 'u-spam.gq',
  'u-spam.ml', 'u-spam.tk', 'valemail.net', 'venompen.com', 'veryrealemail.com',
  'vidchart.com', 'viditag.com', 'viewcastmedia.com', 'viewcastmedia.net', 'viewcastmedia.org',
  'vinb.com', 'viralplays.com', 'vistomail.com', 'vomoto.com', 'voxelcore.com',
  'vpn.st', 'vsimcard.com', 'vubby.com', 'walala.org', 'walkmail.net',
  'wants.dicksinmyan.us', 'watch-email.com', 'watchfull.net', 'watchiron.net', 'web-mail.ga',
  'web-mail.gq', 'web-mail.ml', 'web-mail.tk', 'webemail.me', 'webm4il.info',
  'webmail.igg.biz', 'webm.pro', 'weg-werf-email.de', 'wegwerf-email-addressen.de', 'wegwerf-email.at',
  'wegwerf-email.de', 'wegwerf-email.net', 'wegwerf-emails.de', 'wegwerfadresse.de',
  'wegwerfemail.com', 'wegwerfemail.de', 'wegwerfemail.net', 'wegwerfemail.org',
  'wegwerfemailadresse.com', 'wegwerfmail.de', 'wegwerfmail.info', 'wegwerfmail.net',
  'wegwerfmail.org', 'wetrainbayarea.com', 'wetrainbayarea.org', 'wh4f.org', 'whatiaas.com',
  'whatpaas.com', 'whatsaas.com', 'whopy.com', 'whtjddn.com', 'whyspam.me',
  'wickmail.net', 'wilemail.com', 'willhackforfood.biz', 'willselfdestruct.com', 'winemaven.info',
  'wmail.cf', 'wmail.ga', 'wolke7.net', 'wollan.info', 'world-email.ga',
  'world-email.gq', 'world-email.ml', 'world-email.tk', 'wovz.com', 'wr.moza.pl',
  'wronghead.com', 'wuzupmail.net', 'www.e4ward.com', 'www.gishpuppy.com', 'www.mailinator.com',
  'wwwnew.eu', 'x.ip6.li', 'xagloo.com', 'xemaps.com', 'xents.com',
  'xmail.com', 'xmaily.com', 'xoxox.cc', 'xoxy.net', 'x-spam.gq',
  'x-spam.ml', 'x-spam.tk', 'xww.ro', 'xyzfree.net', 'yapped.net',
  'yeah.net', 'yep.it', 'yert.ye', 'yogamaven.com', 'yomail.info',
  'yopmail.com', 'yopmail.fr', 'yopmail.net', 'yopmail.pp.ua', 'yopmail.us',
  'you-spam.com', 'youmail.ga', 'youmail.gq', 'youmail.ml', 'youmail.tk',
  'yourdomain.com', 'youremail.cf', 'youremail.ga', 'ypmail.webarnak.fr.eu.org', 'yuurok.com',
  'yx.dmarc.io', 'z-o-e.com', 'z1p.biz', 'za.com', 'zebins.com',
  'zebins.eu', 'zehnminuten.de', 'zehnminutenmail.de', 'zeta-telecom.com', 'zetmail.com',
  'zippymail.info', 'zoaxe.com', 'zoemail.com', 'zoemail.net', 'zoemail.org', 'zomg.info',
  'zxcv.com', 'zxcvbnm.com', 'zzz.com'
]);

export const isDisposableEmail = (email: string): boolean => {
  if (!email || !email.includes('@')) {
    return false;
  }
  const domain = email.split('@')[1].toLowerCase();
  return disposableEmailDomains.has(domain);
};
